= Glossary

Accredited key certification centers (AKCC)::
State-accredited organizations that provide digital signature services and secure key information carriers or use the applicant's carriers like USB flash drives.
They play a vital role in maintaining the security and integrity of digital transactions and communications, ensuring the authenticity of digital signatures, and thus enabling secure and trustworthy electronic interactions.

Admin console interface:: xref:#control-plane[Control Plane]

Admin portal:: xref:#administrative-portal[Administrative portal]

[#administrative-portal]
Administrative portal:: A client web application for administering registry regulations. The interface makes it easy to perform necessary configurations without advanced programming skills.

Administrative service:: A service that involves changing some status or other data in a registry. The Platform implements this as a business process that makes changes to the registry data.

Analytical database::
A read-only database used by analytical tools, particularly Redash. It receives registry data through logical replication from the operational database.

[#analytical-report]
Analytical reports:: Preconfigured registry statistics built using the Redash, analytical reporting service.
It may include graphs, tables, visualizations, metrics, or key performance indicators—KPIs.

Authentication::
Verification of the user's provided identifier.

Authorization::
Granting and verification of rights to perform any operations in the system.

Bulk user import::
Creating many user accounts at a time for service providers (officers) in the registry by importing a CSV file.

Business process:: A set of operations aimed at achieving a certain result through data processing.
BPMN models of business processes are part of the registry regulations.

Business Process Model and Notation (BPMN)::
A standard of graphical notation for modeling business processes.

Business processes history database:: A database that stores significant business processes execution history events (such as a history of business processes initiated by a user, completed business processes, and completed user tasks).

Business processes intermediate database::
A distributed database of key-value pairs that temporarily stores data provided by users through the UI forms of business process tasks.

Business processes operational database::
A relational database that stores deployed models of business processes, the current execution state of process instances, the data generated by them, authorization settings, and general configurations.

Candidate version::
The registry regulations candidate version is а branch version derived from the `master` branch of the registry regulations,
utilized for creating and editing entities such as data models, processes, forms, etc.
Modifications are made through the xref:#administrative-portal[Administrative Portal] to the registry-regulations repository. Developers can incorporate these changes after verification and approval into the master version, a process analogous to Git branch merging.

[#central-components]
Central components:: System components that all registries share.
The cluster contains a single copy of each central component.

[#citizen-auto-registration]
Citizen auto-registration ::
xref:#citizen-onboarding[Citizen onboarding]

Citizen-facing solutions::
Citizen-facing solutions refer to digital applications, platforms, or services specifically designed to facilitate direct interactions between governmental bodies and citizens.
These solutions aim to provide easy access to public services, enhance the efficiency of public service delivery, and improve overall citizen satisfaction.

[#citizen-initial-authentication]
Citizen initial authentication::
xref:#citizen-onboarding[Citizen onboarding]

[#citizen-onboarding]
Citizen onboarding::
The process of creating an account for a digital services recipient (citizen).
This includes creating all the database records necessary for user's interaction with the registry (such as user profile, settings, and roles).

Citizen portal::
A web interface used by service recipients (citizens) to interact with the registry in the form of a client web application.

Cluster (Platform) management::
An abstraction within the xref:#control-plane[Control Plane] that enables you to manage the central components of the platform.

Competence Center (CC)::
A team responsible for delivering consulting services to registry development teams, with a key focus on gathering feature requests and tracking bug reports.

Comprehensive information protection system::
A set of organizational and engineering measures and hardware and software tools that ensure the system's information protection.

Confidential data::
Any data that requires authorization to access it.

[#control-plane]
Control Plane::
A set of components that simplify managing the central components of the platform, enables registry management,
and aggregates links to all web APIs of the central components.

Custom Resource (CR)::
A resource that extends the OpenShift API by defining the configuration of a specific OpenShift instance. Not necessarily available out of the box when installing OpenShift.

Dashboard:: xref:analytical-report[Analytical reports]

[#data-center]
Data Center::
A centralized facility utilized by an organization to store, process, and distribute data and applications.
It houses critical IT operations and equipment including servers, storage systems, and networking hardware.
These centers are often designed with redundancy measures such as backup power supplies, data communication connections, and security controls for high availability and reliability.
They can be privately owned or provided by third-party cloud service providers.

[#data-factory]
Data factory::
The platform subsystem responsible for storing data and providing access to it.

[#data-factory-api]
Data factory API::
A data factory programming interface available to other platform components that provides a set of functions for interacting with registry data.

Data model::
A description of the content, structure, and integrity constraints used to create and maintain a registry database. It is defined using the Liquibase format at the registry regulations level.

Data platform::
xref:#data-factory[Data factory]

Decision Model and Notation (DMN)::
A standard notation for modeling business rules using decision tables.

[#digital-identification-services]
Digital identification services::
Platforms that facilitate the electronic identification and authentication of users conveniently and securely.
They allow users to perform electronic identification through various means.

Digital documents:: Files that users can upload, download, and view through business process task interfaces (xref:#ui-form[UI forms]). Documents are stored in the registry's object storage. The content of digital documents is _not_ the object of operations at the level of business processes.

Digital signature::
In the scope of this document, a digital signature can refer to individual's or legal entity's QES, AdES, or EDS, as well as legal entity's electronic seal. The use of QES or AdES depends on the current legislation requirements.

Digital signature (EDS)::
Electronic data obtained from cryptographic transformation and added to other data or documents to ensure the latter's integrity and origin.

Domain Name System (DNS):: A distributed naming system that converts network resource names into IP addresses.

[#endpoint]
Endpoint::
A point of integration that allows two programs or systems to exchange data. It serves as a bridge for receiving, sending, and updating information between various components of a system or different systems.

Excerpt:: A document generated as part of providing the information services through business processes, which can be downloaded by the user who ordered the information service. Excerpts are presented by separate templates at the registry regulations level.

Form::
xref:#ui-form[UI form]

GitOps approach::
A way of implementing continuous deployment for cloud-native applications.
The main idea of GitOps is that any changes to the configuration of the OpenShift cluster, cluster components,
and Platform components are made by modifying the configuration of these components in their respective Git branches.

Group of registries::
Registries that belong to the same owner and are related.

Information panel::
xref:analytical-report[Analytical reports]

Informational service:: A business process implemented on the level of an individual registry that fetches registry data in a specified form. It usually involves confirming a certain status in the registry. The result of the service is either an excerpt or confirmation of rights.

Installer::
A software archive with installation scripts and Docker images that enables you to automatically deploy a specific version of the Platform to a target environment (cloud or xref:#data-center[data center]) and upgrade the Platform to a particular version, for example, `1.9.5`.

Kong::
A component of the external traffic management subsystem and an API gateway.

[#kubernetes]
Kubernetes::
Kubernetes, often abbreviated as K8s, is an open-source platform for automating deployment, scaling, and managing containerized applications.

Low-code::
An approach to creating, configuring, and modifying systems and applications that require minimal programming.
In the context of the Platform, these are the components that enable this approach.

Master version of the regulations::
The current version of the regulations deployed to the registry instance.

Merge request:: A logical representation of changes relative to the current `master` version of the registry regulations.
Merge requests must pass integrity and quality tests before actually being applied to the `master` version.

Object (data ownership)::
Any entity owned by a subject.

[#officer-initial-authentication]
Officer initial authentication::
xref:#officer-onboarding[Officer onboarding]

[#officer-onboarding]
Officer onboarding::
The process of creating an account for a registry services provider (officer) using data obtained from the xref:#qes[QES] key.
This includes creating all the database records necessary for user's interaction with the registry such as user profile, settings, and roles.

Officer portal::
A web interface used by service providers (officers) to interact with the registry in the form of a client web application.

Open data:: Public information in a format that enables its automated processing by electronic means, as well as free and unlimited access and usage.

OpenShift::
A system for automatic deployment, scaling, and management of applications in containers orchestrated and managed by xref:#kubernetes[Kubernetes].

Operational database:: A database that stores registry data, settings, business process data, and other operational data used by the registry's applications and services.

[#personal-data]
Personal data::
Any information that relates to an identified or identifiable living individual.
Data is classified as _personal_ at the level of creating a registry data model, where appropriate processing and access mechanisms are applied.

Platform (IS "Platform")::
xref:#registries-platform[Digital Services Development Platform]

Platform components::
xref:#central-components[Central components]

Platform digital signature keys:: Keys used for integration with external xref:#digital-identification-services[digital identification providers].

[#registries-platform]
Digital Services Development Platform::
An information system that allows authorized government officers to create and maintain registries using the "Registry as a Service" SaaS model. The system can be deployed either in the cloud or on-premises xref:#data-center[data center], either for a single registry or a group of registries.

Public data::
Any data that does not require authorization to access it.

[#qes]
Qualified Electronic Signature (QES):: The e-signature used to authenticate users and sign the data they provide.

Rate limit::
A limit on the number of requests from a single user.

Realm:: A core concept of the Keycloak service. A realm manages a set of users, credentials, roles, and groups.

Digital Services Development Platform's API::
xref:#data-factory-api[Data factory API]

Registry:: A specialized information resource designed to store and process legally important information about people, their rights and obligations, as well as property and resources.

Registry components::
Platform components installed separately for each registry.

Registry configuration::
A configuration of registry components available in the Control Plane and registry repository in line with the GitOps approach.

Registry data::
Information stored in the registry database.

Registry digital signature keys:: Keys used to sign the transformed data of business forms and excerpts.

Registry pipeline::
A process that applies configuration to the registry.

Registry regulations::
A set of data models, business processes, rules, and settings that define the registry's functions.

Registry regulations deployment:: The procedure for creating or updating registry services,
business processes, and the structure of the registry database following the registry regulations.

Regulations roles::
Roles created during registry regulations deployment and configured in the registry regulations.

[#resource]
Resource ::
xref:#endpoint[Endpoint]

Role-Based Access Control (RBAC)::
A method of access control where privileges are assigned to users not directly but via roles. The management of individual user privileges essentially involves assigning them roles.

[#secure-exchange-gateway]
Secure Exchange Gateway::
A secure software interface for electronic interaction between state systems enables collecting information from external systems.

Service:: One or more business processes in the registry aimed at processing a user's request.

Service provider (officer)::
A system role assigned to government representatives interacting with the registry to perform their official duties.

Service recipient (citizen):: A system role assigned to users who interact with the registry to receive administrative and informational services. This role can be set to an individual, PE's representative, or a legal entity.

Subject (data ownership):: Any natural or legal entity that owns an object.

System roles:: Roles created by the Platform during registry deployment or Platform installation.

[#ui-form]
UI form::
The UI form, available in officer and citizen portals, enables users to submit and view data while completing tasks within the business process.

UI form scheme:: A formal description of a UI form's structure, fields, and validation rules. Presented as a file at the registry regulations level.

Uniform Resource Identifier (URI):: A compact sequence of characters that uniquely identifies a resource on the Internet.

User portal::
A common name for the web interface
used by service recipients (citizens) and service providers (officers) to interact with the system.

User roles:: System roles and regulations roles that are assigned to a user.